# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active: test
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active: prod
spring: 
  profiles: 
    active: prod
    spring :
      freemarker:
        allow-request-override: false
        allow-session-override: false
        cache: true
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        enabled: true
        expose-request-attributes: false
        expose-session-attributes: false
        expose-spring-macro-helpers: true
        prefer-file-system-access: true
        suffix: .ftl
        template-loader-path: classpath:/templates/
        settings.template_update_delay: 0
        settings.default_encoding: UTF-8
        settings.classic_compatible: true
        order: 1
---
# 开发环境配置
spring: 
   profiles:  dev
   datasource:
       url: jdbc:mysql://127.0.0.1:3306/faith?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
       username: root
       password: xyqjay
       driver-class-name: com.mysql.jdbc.Driver
---
# 测试环境配置
spring: 
    profiles:  test
    datasource:
       url: jdbc:mysql://192.168.10.48:3306/faith?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
       username: root
       password: xyqjay
       driver-class-name: com.mysql.jdbc.Driver

---
# 生产环境配置
spring: 
    profiles: prod
    datasource:
       url: jdbc:mysql://127.0.0.1:3306/faith?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
       username: root
       password: xyqjay
       driver-class-name: com.mysql.jdbc.Driver